replicaCount: 1

image:
  repository: techiescamp/pomodoro-backend
  tag: "3.0.0"
  pullPolicy: Always

service:
  type: NodePort
  port: 7000
  nodeport: 30163

configmap:
  mountpath: /app/config.js
  subpath: config.js

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 1Gi

## Configmap template file data
port: 7000
mongourl: mongodb+srv://techiescamp:xuYLPYdWN2jp7mLr@db-pomodoro.irdkx.mongodb.net/?retryWrites=true&w=majority&appName=db-pomodoro
jwt_key: mysecret
session_secret: supersecret
frontend_url: http://10.0.3.221:32749
report_backend_url: http://10.0.3.221:30170
jaeger_trace_url: http://simplest-collector.observability.svc.cluster.local:14268

## Network Policy
policy:
  frontend:
    namespace: fe-pomodoro
    appLabel: frontend
