replicaCount: 1

image:
  repository: techiescamp/pomodoro-frontend
  tag: "3.0.0"
  pullPolicy: Always

configmap:
  mountpath: /app/src/config.js
  subpath: config.js

service:
  type: NodePort
  port: 3000
  nodeport: 32749

## Configmap template file data
jaeger_trace_url: http://simplest-collector.observability.svc.cluster.local:14268
