replicaCount: 1

image:
  repository: techiescamp/pomodoro-report-backend
  tag: "2.0.0"
  pullPolicy: Always

service:
  type: NodePort
  port: 7070
  nodeport: 30170

configmap:
  mountpath: /app/config.js
  subpath: config.js

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 1Gi

## Configmap template file data
port: 7070
mongourl: mongodb+srv://techiescamp:xuYLPYdWN2jp7mLr@db-pomodoro.irdkx.mongodb.net/?retryWrites=true&w=majority&appName=db-pomodoro
jaeger_trace_url: http://simplest-collector.observability.svc.cluster.local:14268
